import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Bath, BedDouble, Building2, ChevronDown, Heart, Home, Menu, Search, SlidersHorizontal, Sparkles, X, Maximize2 } from 'lucide-react';
import './App.css';
import { api } from './lib/api';

const properties = [
  { id: 1, title: 'Light-filled apartment by the bay', type: 'Apartment', purpose: 'Rent', price: 12000, city: 'Tangier', area: 'Malabata', bedrooms: 3, bathrooms: 2, surface: 145, image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=85&w=1200', tag: 'New listing', description: 'A calm, generously proportioned home with a sea-facing balcony, bright interiors and everything you need for effortless city living.', amenities: ['Balcony', 'Parking', 'Furnished'], owner: 'Atlassi verified owner' },
  { id: 2, title: 'Contemporary villa in the Palmeraie', type: 'Villa', purpose: 'Sale', price: 4850000, city: 'Marrakech', area: 'Palmeraie', bedrooms: 4, bathrooms: 3, surface: 390, image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=85&w=1200', tag: 'Featured', description: 'A modern interpretation of a Moroccan retreat, with generous outdoor space, a private pool and views toward the Atlas.', amenities: ['Pool', 'Garden', 'Parking'], owner: 'Atlassi verified owner' },
  { id: 3, title: 'Architect-designed home in Anfa', type: 'House', purpose: 'Sale', price: 6200000, city: 'Casablanca', area: 'Anfa', bedrooms: 4, bathrooms: 3, surface: 310, image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=85&w=1200', tag: 'Editor’s pick', description: 'A composed family residence shaped around light, privacy and indoor-outdoor living in one of Casablanca’s most sought-after neighbourhoods.', amenities: ['Garden', 'Terrace', 'Fireplace'], owner: 'Atlassi verified owner' },
  { id: 4, title: 'A quiet riad in the Medina', type: 'Riad', purpose: 'Sale', price: 2900000, city: 'Fes', area: 'Medina', bedrooms: 5, bathrooms: 4, surface: 280, image: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&q=85&w=1200', tag: 'Rare find', description: 'A restored riad with original zellige, a leafy courtyard and the rare feeling of having your own piece of the old city.', amenities: ['Courtyard', 'Terrace', 'Furnished'], owner: 'Atlassi verified owner' },
  { id: 5, title: 'Sunlit studio near Hassan Tower', type: 'Studio', purpose: 'Rent', price: 6500, city: 'Rabat', area: 'Hassan', bedrooms: 1, bathrooms: 1, surface: 48, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=85&w=1200', tag: 'Move-in ready', description: 'A refined, practical studio in the heart of Rabat, close to the tram, cafés and the city’s cultural landmarks.', amenities: ['Furnished', 'Elevator'], owner: 'Atlassi verified owner' },
  { id: 6, title: 'Ocean-view apartment in Agadir', type: 'Apartment', purpose: 'Rent', price: 9000, city: 'Agadir', area: 'Founty', bedrooms: 2, bathrooms: 2, surface: 110, image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=85&w=1200', tag: 'Sea view', description: 'An easy coastal base with a wide terrace, clean lines and a view that makes every evening feel like a holiday.', amenities: ['Sea view', 'Pool', 'Parking'], owner: 'Atlassi verified owner' },
];
const formatPrice = (value, purpose) => `${new Intl.NumberFormat('en-US').format(value)} MAD${purpose === 'Rent' ? ' / month' : ''}`;

function Logo() { return <div className="logo"><span>atlassi</span><i /></div>; }
function PropertyCard({ property, onOpen, saved, onSave }) { return <article className="property-card" onClick={() => onOpen(property)}><div className="card-image-wrap"><img src={property.image} alt={property.title} /><span className="card-tag">{property.tag}</span><button className={`favorite ${saved ? 'is-saved' : ''}`} aria-label="Save property" onClick={(event) => { event.stopPropagation(); onSave(property.id); }}><Heart size={18} fill={saved ? 'currentColor' : 'none'} /></button></div><div className="card-content"><div className="card-heading"><div><span className="eyebrow">{property.purpose} · {property.type}</span><h3>{property.title}</h3></div><ArrowUpRight size={20} /></div><p className="location">{property.area}, {property.city}</p><div className="property-stats"><span><BedDouble size={16} /> {property.bedrooms} bed</span><span><Bath size={16} /> {property.bathrooms} bath</span><span><Maximize2 size={15} /> {property.surface} m²</span></div><div className="card-footer"><strong>{formatPrice(property.price, property.purpose)}</strong><span>View property</span></div></div></article>; }
function DetailPanel({ property, onClose, onSave, saved, onOffer }) { return <div className="overlay" role="dialog" aria-modal="true" onClick={onClose}><section className="detail-panel" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose} aria-label="Close"><X size={20} /></button><div className="detail-hero"><img src={property.image} alt={property.title} /><div className="detail-hero-copy"><span className="eyebrow">{property.purpose} · {property.type}</span><h2>{property.title}</h2><p>{property.area}, {property.city}</p></div></div><div className="detail-body"><div className="detail-main"><div className="price-row"><strong>{formatPrice(property.price, property.purpose)}</strong><button className={`text-action ${saved ? 'is-saved' : ''}`} onClick={() => onSave(property.id)}><Heart size={17} fill={saved ? 'currentColor' : 'none'} /> {saved ? 'Saved' : 'Save'}</button></div><div className="large-stats"><span><BedDouble /> <b>{property.bedrooms}</b> bedrooms</span><span><Bath /> <b>{property.bathrooms}</b> bathrooms</span><span><Maximize2 /> <b>{property.surface} m²</b></span></div><p className="detail-description">{property.description}</p><h3>What this home offers</h3><div className="amenities">{property.amenities.map((item) => <span key={item}>{item}</span>)}</div></div><aside className="contact-card"><span className="verified-dot"><Sparkles size={15} /> Verified listing</span><h3>Ready to make it yours?</h3><p>Ask a question, schedule a visit or make an offer directly to the owner.</p><button className="primary-button">{property.purpose === 'Rent' ? 'Request a visit' : 'Start a conversation'}</button><button className="secondary-button" onClick={() => onOffer(property)}>Make an offer</button><small>{property.owner}</small></aside></div></section></div>; }

function OfferModal({ property, onClose }) { const [amount, setAmount] = useState(''); const [message, setMessage] = useState(''); const [state, setState] = useState('idle'); const submit = async (event) => { event.preventDefault(); setState('loading'); try { await api(`/listings/${property.id}/offers`, { method: 'POST', body: JSON.stringify({ amount: Number(amount), message }) }); setState('success'); } catch (error) { setState(error.message); } }; return <div className="overlay" role="dialog" aria-modal="true" onClick={onClose}><form className="offer-modal" onSubmit={submit} onClick={(event) => event.stopPropagation()}><button type="button" className="close-button" onClick={onClose}><X size={20} /></button><span className="eyebrow">Make an offer</span><h2>{property.title}</h2><p className="offer-price">Listed at {formatPrice(property.price, property.purpose)}</p>{state === 'success' ? <div className="success-message"><Sparkles size={25} /><h3>Offer sent.</h3><p>The owner will be able to review your offer from their dashboard.</p><button type="button" className="primary-button" onClick={onClose}>Done</button></div> : <><label>Your offer amount<input required type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="e.g. 8500" /></label><label>Message <textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Tell the owner a little about your interest..." /></label>{state !== 'idle' && state !== 'loading' && <p className="form-error">{state}</p>}<button className="primary-button" disabled={state === 'loading'}>{state === 'loading' ? 'Sending…' : 'Submit offer'} <ArrowUpRight size={17} /></button></>}</form></div>; }

function App() {
  const [activeTab, setActiveTab] = useState('Buy'); const [query, setQuery] = useState(''); const [city, setCity] = useState(''); const [type, setType] = useState(''); const [showFilters, setShowFilters] = useState(false); const [selected, setSelected] = useState(null); const [offerProperty, setOfferProperty] = useState(null); const [saved, setSaved] = useState(() => JSON.parse(localStorage.getItem('atlassi-favorites') || '[]')); const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => localStorage.setItem('atlassi-favorites', JSON.stringify(saved)), [saved]);
  const filtered = useMemo(() => properties.filter((property) => { const matchesTab = activeTab === 'Buy' ? property.purpose === 'Sale' : activeTab === 'Rent' ? property.purpose === 'Rent' : true; const search = `${property.title} ${property.city} ${property.area} ${property.type}`.toLowerCase(); return matchesTab && (!query || search.includes(query.toLowerCase())) && (!city || property.city === city) && (!type || property.type === type); }), [activeTab, city, query, type]);
  const toggleSave = (id) => setSaved((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); const scrollToListings = () => document.getElementById('discover')?.scrollIntoView({ behavior: 'smooth' });
  return <div className="app-shell"><header className="site-header"><div className="nav-inner"><a href="#top" aria-label="Atlassi home"><Logo /></a><nav className={menuOpen ? 'open' : ''}><a href="#discover">Buy</a><a href="#discover">Rent</a><a href="#requests">Requests</a><a href="#about">About Atlassi</a></nav><div className="header-actions"><button className="post-link" onClick={() => alert('Property publishing will be available after account verification.')}>Post a property <ArrowUpRight size={16} /></button><button className="account-button">Log in</button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">{menuOpen ? <X /> : <Menu />}</button></div></div></header>
  <main id="top"><section className="hero"><div className="hero-orb" /><div className="hero-copy"><span className="kicker"><span /> A new way to find home in Morocco</span><h1>Find a place<br /><em>that feels like you.</em></h1><p>Discover considered homes across Morocco — from a city apartment to a villa by the sea.</p><div className="hero-search"><div className="search-field"><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && scrollToListings()} placeholder="Search by city, neighbourhood or property" /></div><button onClick={scrollToListings}>Search homes <ArrowUpRight size={18} /></button></div><div className="hero-trust"><span><Sparkles size={16} /> Curated listings</span><span><Building2 size={16} /> Morocco-wide</span><span><Home size={16} /> Built for real life</span></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=85&w=1600" alt="Moroccan villa with pool" /><div className="hero-image-caption"><span>Featured home</span><strong>Dar Atlas · Marrakech</strong><small>View collection <ArrowUpRight size={14} /></small></div></div></section>
  <section className="discover-section" id="discover"><div className="section-intro"><div><span className="eyebrow">The Atlassi collection</span><h2>Find your next<br /><em>chapter.</em></h2></div><p>Thoughtfully selected homes, from the everyday to the extraordinary. Search at your pace, then connect with the people behind each place.</p></div><div className="search-toolbar"><div className="tabs">{['Buy', 'Rent', 'All homes'].map((tab) => <button key={tab} className={activeTab === tab ? 'active' : ''} onClick={() => setActiveTab(tab)}>{tab}</button>)}</div><div className="toolbar-controls"><select value={city} onChange={(event) => setCity(event.target.value)} aria-label="Filter by city"><option value="">All cities</option>{[...new Set(properties.map((item) => item.city))].map((item) => <option key={item}>{item}</option>)}</select><select value={type} onChange={(event) => setType(event.target.value)} aria-label="Filter by property type"><option value="">All types</option>{[...new Set(properties.map((item) => item.type))].map((item) => <option key={item}>{item}</option>)}</select><button className={`filter-button ${showFilters ? 'active' : ''}`} onClick={() => setShowFilters(!showFilters)}><SlidersHorizontal size={17} /> Filters <ChevronDown size={15} /></button></div></div>{showFilters && <div className="filter-drawer"><span>Use city, type, purpose and search to narrow your view.</span><button onClick={() => { setCity(''); setType(''); setQuery(''); }}>Clear all</button></div>}<div className="results-meta"><span><strong>{filtered.length}</strong> homes to explore</span><span>Curated for Morocco <Sparkles size={15} /></span></div>{filtered.length ? <div className="property-grid">{filtered.map((property) => <PropertyCard key={property.id} property={property} onOpen={setSelected} saved={saved.includes(property.id)} onSave={toggleSave} />)}</div> : <div className="empty-state"><Sparkles size={26} /><h3>Nothing matches just yet.</h3><p>Try a different search, or tell owners what kind of home you’re looking for.</p><button className="primary-button" onClick={() => document.getElementById('requests')?.scrollIntoView({ behavior: 'smooth' })}>Post a property request <ArrowUpRight size={17} /></button></div>}</section>
  <section className="request-banner" id="requests"><div className="request-mark">?</div><div><span className="eyebrow">Looking for something specific?</span><h2>Nothing matches?<br /><em>Tell us what you need.</em></h2><p>Post a request and let property owners across Morocco come to you.</p></div><button className="light-button" onClick={() => alert('Request posting will open after account creation.')}>Post a request <ArrowUpRight size={17} /></button></section><section className="values-section" id="about"><span className="eyebrow">A more human marketplace</span><h2>Less scrolling.<br /><em>More belonging.</em></h2><div className="values-grid"><div><strong>01</strong><h3>Homes with a point of view</h3><p>We favour places with character, context and a story worth stepping into.</p></div><div><strong>02</strong><h3>Local by design</h3><p>From Tangier to Agadir, Atlassi is grounded in the cities and communities we serve.</p></div><div><strong>03</strong><h3>Clarity at every step</h3><p>See the details that matter, connect with confidence and move at your own pace.</p></div></div></section></main><footer><Logo /><span>© 2026 Atlassi · Made for finding home in Morocco</span><a href="#top">Back to top <ArrowUpRight size={15} /></a></footer>{selected && <DetailPanel property={selected} onClose={() => setSelected(null)} onSave={toggleSave} onOffer={setOfferProperty} saved={saved.includes(selected.id)} />}{offerProperty && <OfferModal property={offerProperty} onClose={() => setOfferProperty(null)} />}</div>;
}
export default App;
